import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Nav from "@/components/Header/Nav";
import ThemeProvider from "@/components/ThemeProvider";
import { Provider } from "jotai";

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            <Nav />
            <main className="mx-auto  max-w-screen-xl  px-6">{children}</main>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
